# Generated by Django 4.1.7 on 2023-02-19 07:55

from django.db import migrations, models
import django.db.models.deletion
import recipe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('material', models.TextField()),
                ('cook', models.TextField()),
                ('recommend', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('share', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('전체', '전체'), ('회/샐러드', '회/샐러드'), ('구이', '구이'), ('튀김', '튀김'), ('찜/탕', '찜/탕'), ('면', '면')], default='전체', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=recipe.models.image_upload_path)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipe.recipe')),
            ],
            options={
                'db_table': 'recipe_image',
            },
        ),
    ]
