version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      # - --default-authentication-plugin=mysql_native_password 
      # - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - .dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db