version: "3.9"

services:
  nginx:
    image: nginx:latest
    build: 
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .dbdata:/var/lib/mysql

  web:
    build: ./
    command: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --build 0.0.0.0:8000
    # volumes:
    #   - ./app:/app
    expose:
      - "8000:8000"
    depends_on:
      - mysql
# version: "3.9"
# services:
#   app:
#     image: myproject
#     container_name: myproject
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     command: /app/entrypoint.sh
#   db:
#     image: mysql:5.7
#     container_name: myproject-db
#     environment:
#       MYSQL_DATABASE: myproject
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_HOST: db
#       MYSQL_PORT: 3306
#     volumes:
#       - db-data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     command: "--default-authentication-plugin=mysql_native_password"
#   nginx:
#     image: nginx:latest
#     container_name: myproject-nginx
#     depends_on:
#       - app
#     volumes:
#       - ./config/nginx:/etc/nginx/conf.d/
#       - static-data:/usr/share/nginx/html/
#     ports:
#       - "80:80"
# volumes:
#   db-data:
#   static-data: