version: "3.9"

services:
  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles/
    depends_on:
      - web

  mysql:
    container_name: mysql
    image: mysql:8
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      # - --default-authentication-plugin=mysql_native_password 
      # - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD-SHELL", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  web:
    build: 
      context: .
    expose:
      - "8000"
    restart: always
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles/
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    links:
      - mysql:mysql
    depends_on:
      - mysql

volumes:
  static_volume: