# Generated by Django 4.0.5 on 2023-07-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_hits_alter_recipe_recommend_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['id'], name='recipe_reci_id_1361ae_idx'),
        ),
    ]
